name: Documentation build
on:
    push:
        branches: ["main"]
        paths:
        - "torchaug/**"
        - "docs/**"
        - "README.md"
    pull_request:
        branches: ["main"]
        paths:
        - "torchaug/**"
        - "docs/**"
        - "README.md"
permissions:
    contents: write
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f docs/requirements.txt ]; then pip install -r docs/requirements.txt; fi
      - name: Sphinx build
        run: |
          sphinx-build docs/source _build
